### ISSUE TITLE
Allow ES6 code

### ISSUE THREAD

**Issue by Skaty** [samsontmr/oss-bot-js#15]
Use something like Babel.

That way, we can have code that is much neater and that will look less quirky.

**Comment by samsontmr** [comment]
What do you mean? Examples? XD

**Comment by Skaty** [comment]
http://es6-features.org/#Constants

**Comment by li-kai** [comment]
Yep, also not instantiating variables with `var/let/const` is very bad code! It's setting variables in the global scope. ES6 will explicitly prevent silly things like this from happening because your code will not run 😛

**Comment by li-kai** [comment]
@Skaty @samsontmr Actually if node 6 and above is used, you can start writing es6 already. No need to transpile.
