### ISSUE TITLE
Line 24 of index.js causing bot to crash on starting in Heroku

### ISSUE THREAD

**Issue by samsontmr** [samsontmr/oss-bot-js#32]
@Skaty @li-kai 

<img width="523" alt="capture" src="https://cloud.githubusercontent.com/assets/15007950/23979965/c408a298-0a37-11e7-8e99-b66b5e1d4d9c.PNG">

**Comment by Skaty** [comment]
Check the version of node that is running on Heroku. You need at least node 6.
